---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -f .htaccess $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp -f .env* $DEPLOYPATH/ 2>/dev/null || true
    - echo "PHP Site Deployment complete at $(date)" > $DEPLOYPATH/deployment_last_run.txt
